# Generated by Django 2.2.3 on 2019-07-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='sample',
        ),
    ]
